import { Artwork, ArtworkFormik } from "../model/artwork.model";

export const mapArtworksFromApi = (artwork: Artwork): ArtworkFormik =>
  ({
    _id: artwork._id,
    Title: artwork.Title,
    Artist: artwork.Artist.join(', '),
    ConstituentID: artwork.ConstituentID?.[0],
    ArtistBio: artwork.ArtistBio?.join(', ') ?? '',
    Nationality: artwork.Nationality?.join(', ') ?? '',
    BeginDate: artwork.BeginDate?.[0],
    EndDate: artwork.EndDate?.[0],
    Gender: artwork.Gender?.join(', ') ?? '',
    Date: artwork.Date,
    Medium: artwork.Medium ?? '',
    Dimensions: artwork.Dimensions ?? '',
    CreditLine: artwork.CreditLine ?? '',
    AccessionNumber: artwork.AccessionNumber ?? '',
    Classification: artwork.Classification,
    Department: artwork.Department ?? '',
    DateAcquired: artwork.DateAcquired ?? '',
    Cataloged: artwork.Cataloged ?? '',
    ObjectID: artwork.ObjectID,
    URL: artwork.URL,
    ImageURL: artwork.ImageURL ?? '',
    OnView: artwork.OnView ?? '',
    'Height (cm)': artwork['Height (cm)'],
    'Width (cm)': artwork['Width (cm)'],
});

export const mapArtworksToApi = (artwork: ArtworkFormik): Artwork => ({
    Title: artwork.Title,
    Artist: artwork.Artist.split(',').map((a) => a.trim()),
    ConstituentID: artwork.ConstituentID !== undefined ? [artwork.ConstituentID] : [],
    ArtistBio: artwork.ArtistBio ? artwork.ArtistBio.split(',').map((b) => b.trim()) : [],
    Nationality: artwork.Nationality ? artwork.Nationality.split(',').map((n) => n.trim()) : [],
    BeginDate: artwork.BeginDate !== undefined ? [artwork.BeginDate] : [],
    EndDate: artwork.EndDate !== undefined ? [artwork.EndDate] : [],
    Gender: artwork.Gender ? artwork.Gender.split(',').map((g) => g.trim()) : [],
    Date: artwork.Date,
    Medium: artwork.Medium || '',
    Dimensions: artwork.Dimensions || '',
    CreditLine: artwork.CreditLine || '',
    AccessionNumber: artwork.AccessionNumber || '',
    Classification: artwork.Classification,
    Department: artwork.Department || '',
    DateAcquired: artwork.DateAcquired || '',
    Cataloged: artwork.Cataloged || '',
    ObjectID: artwork.ObjectID,
    URL: artwork.URL,
    ImageURL: artwork.URL || '',
    OnView: artwork.OnView || '',
    'Height (cm)': artwork['Height (cm)'],
    'Width (cm)': artwork['Width (cm)'],
});